### ISSUE TITLE
Add support for additional activation OTP

### ISSUE THREAD

**Issue by kober32** [wultra/swift-lime-auth#111]
Crypto overview: https://github.com/wultra/powerauth-crypto/blob/issues/323-additional-activation-otp/docs/Additional-Activation-OTP.md
SDK branch: https://github.com/wultra/powerauth-mobile-sdk/commits/issues/278-additional-activation-otp

**Comment by hvge** [comment]
FYI, there's one more change that's important for this ticket. Check wultra/powerauth-mobile-sdk#289
