### ISSUE TITLE
Review access modifiers

### ISSUE THREAD

**Issue by kober32** [wultra/swift-lime-auth#44]
A big portion of the code is unnecessarily `open` or `public` (like auth-keyboard view controllers - e.g. `EnterFixedPasscodeViewController`).

**Comment by hvge** [comment]
Just for note. In my original idea, this was intended, to allow advanced customization in controllers or in storyboards.

This is a low priority. But in general, I don't see benefits in hiding that interfaces.

**Comment by kober32** [comment]
I'm closing this until we'll have serious 3rd party partner for this library
