### ISSUE TITLE
Simplify Password and Passcode View Controllers

### ISSUE THREAD

**Issue by kober32** [wultra/swift-lime-auth#45]
In `***PasscodeViewController` and `***PasswordViewController` classes is a huge portion of duplicated code and logic that could be simplified through components and inheritance.

**Comment by hvge** [comment]
I would prefer components over the inheritance. Here are some of my ideas:

- We should move the logic of PIN keyboard to a controller. Right now it's a view with functionality similar to controller, but requires a lot of duplicity in the storyboards. Each "PIN" enter / create controller has its own copy of PIN keyboard views, which makes future changes in the PIN keyboard, quite complex task.
- We should create a component for presenting variable PIN with OK button.
- We should create a similar component for presenting password text field with OK button.

The last two ideas also leads to simplified storyboards, plus it may allow us to switch between the visual styles. For example, right now there's a hardcoded border over the password & OK button, but that may not be always wanted by the client.

This is low priority enhancement. We don't need to invest in this.
