### ISSUE TITLE
Activation code validation

### ISSUE THREAD

**Issue by kober32** [wultra/swift-lime-auth#85]
Activation code should be validated _after_ the user hits the `Confirm` button. Otherwise, the user doesn't have a clue, why is button disabled even when he provided code (length is OK, only CRC failed).

**Comment by kober32** [comment]
The same goes for the PUK and Recovery Code that will be in Recovery Activation flow

**Comment by hvge** [comment]
You forgot to implement the same change for "activation recovery" flow. I'm reopening this issue.

**Comment by kober32** [comment]
Damn :( ok, I'm on it
